### ISSUE TITLE
datos de contacto

### ISSUE THREAD

**Issue by jorgecardenas9006** [mariaroa/curriculum#2]
Pertenezco a la ciudad de mexico y cuando marco el numero 3192216882 no me funciona. Por favor indicar a donde me debo comunicar, ya que en Mexico el codigo es +54.

**Comment by mariaroa** [comment]
Resuelto, gracias.

**Comment by jorgecardenas9006** [comment]
Muchas gracias, ya quedo resuelto el incidente.
